DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS plans;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL UNIQUE,
	phone_number INTEGER NOT NULL UNIQUE,
	group_id INTEGER NOT NULL UNIQUE
);

CREATE TABLE groups (
	id SERIAL PRIMARY KEY,
	group_name TEXT NOT NULL UNIQUE
);

CREATE TABLE plans (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL UNIQUE,
	location VARCHAR(100) NOT NULL,
);